export default {
  font: [
    'Helvetica',
    'Arial',
    'Times New Roman',
    'Calibre',
    'Georgia',
    'Brush Script MT',
    'Courier New',
    'bloddy',
    'FirecatMedium',
    'Headhunter-Regular',
    'plasdrip',
    'plasdrpe',
  ],
  font_size: ['26px', '28px', '30px', '32px', '34px', '36px', '38px', '40px'],
  font_color: ['white', 'black'],
  background_color: ['#FF5733', '#33FF61', '#147CC4', '#AF3200', '#E51125'],
  rotate: [
    'rotate(-10deg);',
    'rotate(-5deg);',
    'rotate(0deg);',
    'rotate(0deg);',
    'rotate(5deg);',
    'rotate(10deg);',
  ],
  text_transformation: ['uppercase', 'lowercase'],
  text_decoration: ['underline', 'overline', 'none', 'none'],
  font_style: ['bold', 'regular', 'regular', 'italic'],
  padding: ['0em', '0.1em', '0.2em', '0.3em'],
  margin: ['0em', '0.1em', '0.2em', '0.3'],
}
